### ISSUE TITLE
C2 much slower than VC1?

### ISSUE THREAD

**Issue by mrliptontea** [scaleway-community/scaleway-gitlab#27]
Hi, I'm planning to move my company's GitLab to Scaleway, so I created a new server with your image but ran into an issue.

Image currently ships with GitLab 8.6.5, so I run an update. It was taking a very long time, so I did some more testing, and these are the results:

On **C2S**

```
$ time sudo apt-get install gitlab-ce=8.9.0-ce.0
...
real    31m28.160s
user    3m32.750s
sys     1m3.850s
```

on **VC1L**

```
$ time sudo apt-get install gitlab-ce=8.9.0-ce.0
...
real    4m24.776s
user    1m49.170s
sys     0m36.400s
```

The step that is taking most of that time on **C2** is

```
Unpacking gitlab-ce (8.9.0-ce.0) over (8.6.5-ce.0) ...
```

Same thing happens with update 8.9.0 → 8.9.1 and 8.9.1 → 8.9.2. It's just a ~275MB .deb file but it takes over 20 minutes to unpack it on C2 servers, and I already tried that on two different instances.

Why is this happening? Both servers claim to use LSSD drives. I would prefer to use C2 as it has dedicated resources.

**Comment by mrliptontea** [comment]
Today, GitLab release another update, run it, and here are execution times:
```
real    4m14.550s
user    1m4.430s
sys     0m33.437s

# C2
real    33m27.148s
user    1m38.500s
sys     1m1.720s
```

So it doesn't look like a temporary issue.

**Comment by MFrancesco** [comment]
Same here.
Still blocked on unpacking gitlab-ce (8.11.6-ce.0) on a freshly spinned C2S instance.
Should a C2S perform better than a VC1L instance?

**Comment by brmzkw** [comment]
Hi,

First of all, I'm sorry it took us so long to answer this issue. We will release a new Gitlab image pretty soon so you won't have to update it manually.

Anyway, there is indeed an issue when installing package on our baremetal instances. For more details, see this thread on the Linux ext4 mailing list: http://www.spinics.net/lists/linux-ext4/msg54685.html

In short: our baremetal instances have their root file system served by NBD. Behind the scene, `apt-get` calls `dpkg` which extensively uses the `fallocate(2)` system call — and it shouldn't. In the case of NBD devices, calls to `fallocate` are slow. From `dpkg>=1.18.15` the number of calls to `fallocate` has been reduced drastically. Consequently, using an upgraded version of `dpkg` should fix the issue...
However, our gitlab image is based on a debian/jessie image which comes with `dpkg==1.17.27` (compared to debian/stretch which comes with `dpkg==1.18.23 `).

Upgrading the base image to debian/stretch could be an option, but we prefer to stick with a released version.


I close this issue since we will release the image soon and you won't have to upgrade manually anymore.

**Comment by bchatelard** [comment]
Ubuntu Xenial now ships the latest dpkg, this issue should be fixed.
